### PR TITLE
Compile errors

### PR DESCRIPTION
**Pull request by ovenpasta**
I fixed some compile errors. I think it would be better to tidy or document the ffi module in spheres. In the meanwhile this patch fixes the problem. I'm compiling under linux x86_64 (mint)

### CODE REVIEW

**Comment by alvatar** [comment]
Thank you @ovenpasta 
The flags would require /usr/local/include for includes (-I) and /usr/local/lib for linker (-L) on OSX. Do you want me to add it afterwards or you prefer to add them as part of this PR?
I think they should be added before, because they allow users to get their own custom builds of SDL, even on Linux distros, bypassing the distro package management by typical `./configure && make && make install` being found before this way.

**Comment by alvatar** [comment]
What you mention of using `sdl2-config` is actually the best option in my opinion. Then fallback to manually-defined -I and -L options, using the /usr/local as a primary option and /usr as secondary.
What do you think?
Using `with-input-from-process` or a variant and falling back if error to a predefined flags string should do it.

**Comment by ovenpasta** [comment]
Ok I tried some code and seems to work. It uses sdl2-config. I didn't write fallback code yet.
Still a thing that seems need attention is ssrun stuff. It should by default or copy the spheres/sdl2 into ~~lib/spheres/spheres or some other mechanism to find it automatically. At least it should compile!. it's counter intuitive to just fail compiling because of not finding the directory that is actually in the current package

**Comment by alvatar** [comment]
Thank you!
The sdl-config code looks good. I will merge that.
The sdl2.sld file shouldn't be added because these bindings don't use the R7RS module system, they are just plain R5RS. This way we avoid issues between the syntax expander (which is a bit of a mess) and the native Gambit expander dealing with bindings code. When no sld file is present, then the file is loaded normally.

**Comment by alvatar** [comment]
I will merge everything and fix then the way it loads. The issue you mentioned is already logged here: https://github.com/fourthbit/spheres/issues/6

**Pull request merged**
